version: "3.8"

services:

  yelp-ea-front:
    image: maelmichaud/angular-frontend:latest
    ports:
      - "8081:80"

  yelp-ea-back:
    image: maelmichaud/java-backend:latest
    ports:
      - "8080:8080"
    depends_on:
      mysqldb:
        condition: service_healthy

  mysqldb:
    image: mysql:8.0
    ports:
      - "3314:3306"
    volumes:
      - msg-mysql-data:/var/lib/mysql
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  msg-mysql-data:
