name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  backend:

    runs-on: ubuntu-latest

    steps:
    # checkout
    - uses: actions/checkout@v4

    # install java
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      working-directory: YelpEaBack
    # package = test puis jar
      run: mvn -B package --file pom.xml

    # install Docker
    - name: Docker install avec action
      run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
          sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          sudo docker -- version

    # docker build
    - name: Build Docker image
      working-directory: YelpEaBack
      run: |
        docker build -t back .
    # docker login -> action
    # run docker push

#frontend:
 # install angular
 # run npm test
 # test selenium
 # docker login -> action
 # run docker push
